/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../mf_1021.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_1.geometry} material={materials['24,37,248']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_2.geometry} material={materials['191,191,191']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_3.geometry} material={materials['255,254,246']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_4.geometry} material={materials['244,244,244']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_5.geometry} material={materials['231,230,228']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_6.geometry} material={materials['190,188,186']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_7.geometry} material={materials['72,71,61']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_8.geometry} material={materials['177,177,177']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_9.geometry} material={materials['42,42,42']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_10.geometry} material={materials['245,245,245']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_11.geometry} material={materials['64,72,70']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021_12.geometry} material={materials['64,55,56']} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../mf_1021.gltf')
