/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../mf_1121.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_1.geometry} material={materials['24,37,248.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_2.geometry} material={materials['191,191,191.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_3.geometry} material={materials['255,254,246.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_4.geometry} material={materials['244,244,244.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_5.geometry} material={materials['231,230,228.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_6.geometry} material={materials['190,188,186.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_7.geometry} material={materials['72,71,61.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_8.geometry} material={materials['177,177,177.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_9.geometry} material={materials['42,42,42.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_10.geometry} material={materials['245,245,245.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_11.geometry} material={materials['64,72,70.002']} />
        <mesh geometry={nodes.Mycrofish_28_Oktober_2021005_12.geometry} material={materials['64,55,56.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../mf_1121.glb')
