/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['CuteUmbrella_CrossPink_CuteUmbrella_Log556-GRP-378912-CrossPink'].geometry}
        material={materials.CrossPink_001}
        rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes['CuteUmbrella_001_CuteUmbrella_Log556-GRP-378912-2'].geometry}
          material={materials['2.001']}
        />
        <mesh geometry={nodes['CuteUmbrella_002_CuteUmbrella_Log556-GRP-378912-__'].geometry} material={materials.__} />
        <mesh
          geometry={nodes['CuteUmbrella_Material_CuteUmbrella_Log556-GRP-378912-Default_Ma'].geometry}
          material={materials.Default_Material}
        />
        <mesh
          geometry={nodes['CuteUmbrella_White_CuteUmbrella_Log556-GRP-378912-White'].geometry}
          material={materials.White}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('../../../model.gltf')
