/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../mycrofish.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.MVP_Kecil_Agustus_2021_1.geometry} material={materials['24,37,248']} />
        <mesh geometry={nodes.MVP_Kecil_Agustus_2021_2.geometry} material={materials['191,191,191']} />
        <mesh geometry={nodes.MVP_Kecil_Agustus_2021_3.geometry} material={materials['255,254,246']} />
        <mesh geometry={nodes.MVP_Kecil_Agustus_2021_4.geometry} material={materials['244,244,244']} />
        <mesh
          geometry={nodes.MVP_Kecil_Agustus_2021_5.geometry}
          material={materials.DC2AD1790C01CAF1DE18E4DD123FF28B369B88E2}
        />
        <mesh geometry={nodes.MVP_Kecil_Agustus_2021_6.geometry} material={materials['190,188,186']} />
        <mesh geometry={nodes.MVP_Kecil_Agustus_2021_7.geometry} material={materials['105,105,105']} />
        <mesh
          geometry={nodes.MVP_Kecil_Agustus_2021_8.geometry}
          material={materials['840EDFE9E54295EC0CCFCC6B8A57544615D92180']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../../mycrofish.glb')
